
const hre = require("hardhat");
const { ethers } = hre;

function namehash(name) {
  let node = "0x" + "00".repeat(32);
  if (!name) return node;
  const labels = name.split(".");
  for (let i = labels.length - 1; i >= 0; i--) {
    const labelHash = ethers.keccak256(ethers.toUtf8Bytes(labels[i]));
    node = ethers.keccak256(ethers.concat([node, labelHash]));
  }
  return node;
}

const ENS_REGISTRY = "0x00000000000C2E074eC69A0dFb2997BA6C7d2e1e";
const PUBLIC_RESOLVER = "0xE99638b40E4Fff0129D56f03b55b6bbC4BBE49b5";

async function main() {
  const [deployer] = await ethers.getSigners();
  console.log("Deployer:", deployer.address);

  const Verifier = await ethers.getContractFactory("Verifier").catch(()=>null);
  if (!Verifier) throw new Error("Place Verifier.sol generated by nargo into contracts/contracts/Verifier.sol");

  const verifier = await Verifier.deploy();
  await verifier.waitForDeployment();
  console.log("Verifier:", await verifier.getAddress());

  const PG = await ethers.getContractFactory("PaymentGateway");
  const gateway = await PG.deploy(ENS_REGISTRY, PUBLIC_RESOLVER, await verifier.getAddress(), false, ethers.ZeroAddress);
  await gateway.waitForDeployment();
  console.log("PaymentGateway:", await gateway.getAddress());

  console.log("\nCopy to frontend:");
  console.log("GATEWAY_ADDRESS=", await gateway.getAddress());
  console.log("COMPANY_NODE=", namehash("company.eth"));
}

main().catch(e=>{ console.error(e); process.exit(1); });
