// SPDX-License-Identifier: MIT
pragma solidity ^0.8.24;

// Mock verifier for local development only. Always returns true.
// Replace this file with the Solidity verifier generated by `nargo codegen-verifier` for production.
contract Verifier {
    // Accept any proof/publicInputs in local testing
    function verify(bytes calldata /*proof*/, bytes32[] calldata /*publicInputs*/) external pure returns (bool) {
        return true;
    }
}
